export const ActionTypes = {
  GET_TASKS: "GET_TASKS",
  CREATE_TASK: "CREATE_TASK",
  COMPLETE_TASK: "COMPLETE_TASK",
  DELETE_TASK: "DELETE_TASK",
  RESTORE_TASK: "RESTORE_TASK",
  PRIORITIZE_TASK: "PRIORITIZE_TASK",
  GET_NOTES: "GET_NOTES",
  CREATE_NOTE: "CREATE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
};
